config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_USERNAME'])) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_PASSWORD']))
  end if Rails.env.production?

  mount Sidekiq::Web => '/sidekiq'

  resources :passwords, controller: 'clearance/passwords', only: %i[create new]
  resource :session, controller: 'clearance/sessions', only: [:create]

  resources :users, controller: 'users', only: [:create] do
    resource :password,
             controller: 'clearance/passwords',
             only: %i[create edit update]
  end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/sign_up' => 'clearance/users#new', as: 'sign_up'

  resources :vacancies

  namespace :company do
    resources :vacancies, only: [:index]
  end

  root to: 'vacancies#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  URL_REGEX = /\A^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$\Z/ix

  has_many :users
  has_many :vacancies

  validates :name, :url, presence: true
  validates :url, format: { with: URL_REGEX }

  before_validation do
    self.url = "http://#{url}" unless url.nil? || url[0, 4] == 'http'
  end
end

app/models/searchs/vacancy.rb
# frozen_string_literal: true

module Searchs
  class Vacancy
    def initialize(repository = ::Vacancy.joins(:company).recent)
      @repository = repository
    end

    def list(query = nil)
      return @repository.recent if query.blank?

      query = query.split.map { |entry| "#{entry}:*" }.join(' & ')

      @repository.where(<<~SQL, query: query)
        tsv @@ to_tsquery('portuguese', :query) OR company_tsv @@ to_tsquery('portuguese', :query)
      SQL
    end

    def self.list(query = nil)
      new.list(query)
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Clearance::User

  belongs_to :company

  accepts_nested_attributes_for :company

  delegate :name, to: :company, prefix: true
end

app/models/vacancy.rb
# frozen_string_literal: true

class Vacancy < ApplicationRecord
  include FriendlyId

  MAX_VALID_PERIOD = 30.days

  friendly_id :slug_candidates, use: :slugged

  belongs_to :company
  delegate :name, :url, to: :company, prefix: true, allow_nil: true

  scope :recent, -> { where(created_at: MAX_VALID_PERIOD.ago.beginning_of_day..Time.zone.now).order(created_at: :desc) }

  validates :job_title, :location, :description, :how_to_apply, presence: true

  private

  def slug_candidates
    [
      %i[company_name job_title]
    ]
  end
end

app/models/vacancy/publish.rb
# frozen_string_literal: true

class Vacancy
  class Publish
    def initialize(worker: NotifyVacancyWorker)
      @worker = worker
    end

    def publish(vacancy)
      vacancy.save!
      @worker.perform_async(vacancy.id)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# :nodoc:
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception

  private

  def current_company
    current_user.company
  end
end

app/controllers/company/vacancies_controller.rb
# frozen_string_literal: true

class Company::VacanciesController < ApplicationController # rubocop:disable Style/ClassAndModuleChildren
  before_action :require_login

  def index
    @vacancies = current_company.vacancies
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < Clearance::UsersController
  private

  def user_params
    params.require(:user).permit(:email, :password, company_attributes: %i[name url])
  end
end

app/controllers/vacancies_controller.rb
# frozen_string_literal: true

class VacanciesController < ApplicationController
  before_action :require_login, except: %i[index show]

  rescue_from ActiveRecord::RecordInvalid, with: :render_new

  def index
    @search = params[:search]
    @vacancies = Searchs::Vacancy.list(@search)
  end

  def new
    @vacancy = Vacancy.new
  end

  def create
    @vacancy = current_company.vacancies.new(vacancy_params)
    Vacancy::Publish.new.publish(@vacancy)
    flash[:success] = t('.success')
    redirect_to @vacancy
  end

  def show
    @vacancy = Vacancy.friendly.find(params[:id])
  end

  def edit
    @vacancy = current_company.vacancies.friendly.find(params[:id])
  end

  def update
    @vacancy = current_company.vacancies.friendly.find(params[:id])
    @vacancy.update_attributes!(vacancy_params)
    redirect_to @vacancy
  end

  private

  def render_new
    render :new
  end

  def vacancy_params
    params.require(:vacancy).permit(:job_title, :location, :description, :how_to_apply)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: 'alert-success',
      error:   'alert-danger',
      alert:   'alert-block',
      notice:  'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def error_tag(model, attribute)
    return unless model.errors.key?(attribute)

    content_tag(
      :div,
      model.errors[attribute].join(', '),
      class: 'error_message'
    )
  end

  def menu_class(path)
    current_page?(path) ? 'active' : ''
  end

  def no_content_message(message)
    content_tag(:div, content_tag(:h3, message, class: 'no-content'))
  end
end

app/helpers/share_links_helper.rb
# frozen_string_literal: true

module ShareLinksHelper
  PROVIDERS = {
    facebook: { url: 'https://www.facebook.com/sharer/sharer.php?u=#current_page#', icon: 'fa-facebook-official' },
    twitter:  { url: 'https://twitter.com/home?status=Look this job: #current_page#', icon: 'fa-twitter-square' },
    linkedin: { url: 'https://www.linkedin.com/shareArticle?url=#current_page#', icon: 'fa-linkedin-square' }
  }.freeze

  def share_links_to_current_page
    current_page = request.original_url
    content_tag(:p) do
      PROVIDERS.keys.map { |social_network| concat(share_link_for(social_network, current_page)) }
    end
  end

  private

  def share_link_for(social_network, page)
    provider   = PROVIDERS[social_network]
    share_url  = provider[:url].gsub('#current_page#', page)
    link_to(share_url, target: 'blank') do
      content_tag(:i, nil, class: "fa #{provider[:icon]} fa-2x", 'aria-hidden' => true)
    end + ' '
  end
end

app/views/company/vacancies/_vacancy.html.erb
<%= render 'components/vacancy_item', vacancy: vacancy, link: edit_vacancy_path(vacancy.id) %>

app/views/company/vacancies/index.html.erb
<section>
  <div class="row">
    <div class="col-md-12">
      <h1 class="text-center">
        <%= t("vacancies.index.vacancies") %>
      </h1>
    </div>
  </div>
</section>

<section>
  <article>
    <div class="vacancy-list">
      <%= render(@vacancies) || no_content_message(t(".no_vacancies")) %>
    </div>
  </article>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenJobs</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= yield :metatags %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>

  </head>

  <body>
    <!-- Fixed navbar -->
    <%= render "shared/navbar", search: @search %>

    <div class="container">
      <br />
      <%= render partial: "shared/flash_messages", flash: flash %>

      <%= yield %>
    </div> <!-- /container -->

  </body>

  <%= render "shared/footer" %>
  <% if ENV["FULLSTORY_ENABLED"] %>
    <script>
      window['_fs_debug'] = false;
      window['_fs_host'] = 'fullstory.com';
      window['_fs_org'] = '7T1RH';
      window['_fs_namespace'] = 'FS';
      (function(m,n,e,t,l,o,g,y){
        if (e in m) {if(m.console && m.console.log) { m.console.log('FullStory namespace conflict. Please set window["_fs_namespace"].');} return;}
        g=m[e]=function(a,b){g.q?g.q.push([a,b]):g._api(a,b);};g.q=[];
        o=n.createElement(t);o.async=1;o.src='https://'+_fs_host+'/s/fs.js';
        y=n.getElementsByTagName(t)[0];y.parentNode.insertBefore(o,y);
        g.identify=function(i,v){g(l,{uid:i});if(v)g(l,v)};g.setUserVars=function(v){g(l,v)};
        g.identifyAccount=function(i,v){o='account';v=v||{};v.acctId=i;g(o,v)};
        g.clearUserCookie=function(c,d,i){if(!c || document.cookie.match('fs_uid=[`;`]*`[`;`]*`[`;`]*`')){
          d=n.domain;while(1){n.cookie='fs_uid=;domain='+d+
              ';path=/;expires='+new Date(0).toUTCString();i=d.indexOf('.');if(i<0)break;d=d.slice(i+1)}}};
      })(window,document,window['_fs_namespace'],'script','user');
    </script>
      <% end %>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div role="alert" class="alert <%= bootstrap_class_for(type) %> alert-dismissable">
    <button class="close" data-dismiss="alert" aria-label="close"><span aria-hidden="true">&times;</span></button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p class="love">Made with <i class="fa fa-heart"></i> and <i class="fa fa-coffee"></i> by <%= link_to "OpenSanca", "http://opensanca.com.br", target: '_blank' %> folks</p>
</footer>

app/views/shared/_metatags.html.erb
<meta name="description" content="<%= description %>" />
<meta property="og:title" content="<%= title %>" />
<meta property="og:description" content="<%= description %>" />

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        Open<span class="brand-name">Jobs</span>
      <% end %>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="<%= menu_class(root_path) %>"><%= link_to t("menu.all_vacancies"), root_path %></li>
        <% if signed_in? %>
          <li><%= link_to t(".sign_out"), sign_out_path, method: :delete %></li>
          <li><%= link_to t(".my_vacancies"), company_vacancies_path %></li>
        <% end %>
      </ul>

      <%= form_tag vacancies_path, class: "navbar-form navbar-right", method: :get do %>
        <div class="input-group">
          <%= text_field_tag 'search', search, class: 'form-control', placeholder: t("vacancies.search") %>

          <div class="input-group-btn">
            <button class="btn btn-default" type="submit">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </div>
      <% end %>
    </div>
  </div><!--/.nav-collapse -->
</nav>

app/views/users/_form.html.erb
<h1><%= t(".title") %></h1>

<%= form.text_field :email, autofocus: true, class: 'field', type: 'email', placeholder: User.human_attribute_name('email') %>

<%= form.password_field :password, class: 'field', placeholder: User.human_attribute_name('password') %>

<br/>

<h1><%= t(".company_data") %></h1>

<%= form.fields_for :company, @user.company || @user.build_company do |company_form| %>
  <%= company_form.text_field :name, class: 'field', placeholder: Company.human_attribute_name(:name) %>
  <%= company_form.text_field :url,  class: 'field', placeholder: Company.human_attribute_name(:url) %>
<% end %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <div class="login-container">
    <div class="sign-box">
      <% if @user.errors.any? %>
        <ul class="error-list">
          <% @user.errors.full_messages.each do |msg| %>
            <li class="alert-error">
              <%= msg %>
            </li>
          <% end %>
        </ul>
      <% end %>


      <%= form_for @user do |form| %>
        <%= render partial: '/users/form', object: form %>

        <div class="submit-field">
          <%= form.submit class: 'btn btn-sign' %>
        </div>

        <div class="other-links">
          <%= link_to t(".sign_in"), sign_in_path %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/vacancies/_form.html.erb
<%= form_for vacancy do |f| %>
  <div class="form-group">
    <%= f.label :job_title, t('.job_title') %>
    <%= f.text_field :job_title, class: 'form-control' %>
    <%= error_tag vacancy, :job_title %>
  </div>

  <div class="form-group">
    <%= f.label :location, t('.location') %>
    <%= f.text_field :location, class: 'form-control' %>
    <%= error_tag vacancy, :location %>
  </div>

  <div class="form-group">
    <%= f.label :description, t('.description') %>
    <%= f.text_area :description, rows: 15, class: 'form-control', 'data-provider' => 'summernote' %>
    <%= error_tag vacancy, :description %>
  </div>

  <div class="form-group">
    <%= f.label :how_to_apply, t('.how_to_apply') %>
    <%= f.text_area :how_to_apply, rows: 5, class: 'form-control' %>
    <%= error_tag vacancy, :how_to_apply %>
  </div>

  <div class="text-right">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/vacancies/_vacancy.html.erb
<%= render 'components/vacancy_item', vacancy: vacancy, link: vacancy_path(vacancy) %>

app/views/vacancies/edit.html.erb
<h2 class="page-title"><%= t(".edit_vacancies") %></h2>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form', vacancy: @vacancy %>
  </div>
</div>

app/views/vacancies/index.html.erb
<section class="bg-vacancy-intro">
  <div class="row">
    <div class="col-md-12">
      <h1 class="text-center">
        <%= t(".welcome_message_html") %>
      </h1>
      <div class="text-center">
          <%= link_to t(".advertise_message"), new_vacancy_path, class: "btn btn-primary btn-register-vacancy grow" %>
      </div>
    </div>
  </div>
</section>

<section>
  <article>
    <div class="vacancy-list">
      <%= render(@vacancies) || no_content_message(t(".no_vacancies")) %>
    </div>
  </article>
</section>

app/views/vacancies/new.html.erb
<h2 class="page-title"><%= t(".submit_vacancy") %></h2>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form', vacancy: @vacancy %>
  </div>
</div>

app/views/vacancies/show.html.erb
<%= content_for :metatags do %>
  <%= render("shared/metatags", { title: @vacancy.job_title, description: t('metatags.vacancy_description', job_title: @vacancy.job_title, company_name: @vacancy.company_name, location: @vacancy.location) }) %>
<% end %>

<section class="view-vacancy">
  <div class="row">
    <div class="col-md-9">
      <div class="row">
        <div class="col-md-2">
          <%= image_tag("ico-company-default.png", class: 'img-responsive describe-img-company vertical-25') %>
        </div>

        <div class="col-md-8">
          <h1 class="job-title-view"><%= @vacancy.job_title %></h1></h1>
            <table class="table report-vacancy">
              <tr>
                <td><span class="vacancy-describe-itens"> <i class="fa fa-briefcase" aria-hidden="true"></i></span></td>
                <td><%= @vacancy.company_name %></td>
                <td><%= link_to @vacancy.company_url, @vacancy.company_url, target: 'blank' %></td>
              </tr>

              <tr>
                <td><span class="vacancy-describe-itens"> <i class="fa fa-map-marker" aria-hidden="true"></i></span></td>
                <td><%= @vacancy.location %></td>
                <!-- <td> CLT - Remote</td> -->
              </tr>

              <tr>
                <td><span class="vacancy-describe-itens"> <i class="fa fa-calendar" aria-hidden="true"></i> </span></td>
                <td><%= I18n.l(@vacancy.created_at, format: :short) %></td>
              </tr>

          </table>
        </div>

        <div class="col-md-2">
          <%= link_to "#", class: "btn btn-primary btn-border-bottom-primary vertical-25 grow", data: { behavior: "apply-to-job", anchor: "how_to_apply_title" } do %>
            <i class="fa fa-trophy" aria-hidden="true"></i>
            <%= t("messages.apply_for_job") %>
          <% end %>

          <br> <br>
        </div>
      </div> <!--/row-->
    </div><!--/col-md-9-->
    <div class="col-md-3">
      <div class="box-share-vacancy">
        <h4> <i class="fa fa-rocket" aria-hidden="true"></i> <%= t(".recommend") %></h4>
          <p><%= t(".help_friends") %></p>
          <%= share_links_to_current_page %>
      </div>
  </div><!--/col-md-3-->
</div>
</section>

<section class="describe-vacancy">
  <div class="row">
    <div class="col-md-12">

    <h3><%= t(".job_description") %></h3>
      <hr>
    <p class="text-justify">
      <%= sanitize(@vacancy.description) %>
    </p>

    <h3 id="how_to_apply_title" />
      <%= t(".how_to_apply") %>
      <a class="btn-hint" role="button" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        <i class="fa fa-lightbulb-o" aria-hidden="true"></i>
     </a>
    </h3>
      <hr>
    <div class="collapse" id="collapseExample">
      <div class="question-apply">
         <h5></h5>
         <ol>
           <%= t(".apply_help_html") %>
         </ol>
      </div>
    </div>
    <p class="text-jusify" id="how_to_apply">
      <%= @vacancy.how_to_apply %>
    </p>
    </div>
  </div>
</section>